### ISSUE TITLE
JS & JSX Spread operators

### ISSUE THREAD

**Issue by nolimits4web** [phenomejs/phenome#8]
I can't make spread operator to work in both JSX (in arguments) or some component declaration objects. We don't even need to polyfill it (for example with `Object.assign`), as we don't transpile output to es5, so it is fine to keep spread operator as it is in compiled file. But for some reason Babel/Babylon throw errors on it.

@bencompton can you take a look please when you have time?)

**Comment by bencompton** [comment]
I went into the accordion-content component and tried some Spread operator examples, and here is what happened:

```javascript
    const propsObj = {
      id: this.props.id,
      style: this.props.style,
      className: this.classes,
    };

    //Array spread works fine
    const someArray = [1, 2, 3, 4];
    const arrayWithSpread = [...someArray, 5, 6];

    //Object spread fails
    const someObject = { foo: 'test', bar: 'test2' };
    const objectWithSpread = { ...someObject, baz: 'test3' };

   //JSX spread works fine
    return (
      <div {...propsObj}>
        <slot></slot>
      </div>
    );
```

Rest/Spread are still considered experimental and are slated for ES2018. It appears that Babel currently only supports it in [this plugin](https://babeljs.io/docs/plugins/transform-object-rest-spread/). I installed the plug-in and hard-coded `codeToAst` so it would use that plug-in. The Babel compiler stopped erroring on the object Spread, but I had to upgrade `@babel/core` to the latest version to make the plug-in work. Unfortunately, it seems that the latest version of `@babel/core` is causing problems. After calling `babel.transform` in `codeToAst`, the `ast` property is now coming back as `null` for some reason.

Ultimately, we will need to provide the ability to pass in Babel compiler options as you said in #9. That will then allow us to add in the above plug-in to support object Rest/Spread. It appears that we first need to figure out why the latest version is returning a `null` AST.
